@startuml

title __ASSETS's Class Diagram__\n

  namespace joc {
    namespace assets {
      enum AssetList {
        ARROW_BOTTOM
        ARROW_BOTTOM_LEFT
        ARROW_BOTTOM_RIGHT
        ARROW_LEFT
        ARROW_RIGHT
        ARROW_TOP
        ARROW_TOP_LEFT
        ARROW_TOP_RIGHT
        CASTLE_GRASS_TILE
        CASTLE_SAND_TILE
        DAMAGED_CASTLE_GRASS_TILE
        ENEMY_ARCHER_LEFT
        ENEMY_ARCHER_RIGHT
        ENEMY_REGULAR_LEFT
        ENEMY_REGULAR_RIGHT
        ENEMY_ROCK_THROWER_LEFT
        ENEMY_ROCK_THROWER_RIGHT
        GRASS_TILE
        HEART_ICON
        KEY_ICON
        MOUNTAIN_TILE
        PLAYER_LEFT
        PLAYER_RIGHT
        ROCK_BOTTOMLEFT
        ROCK_BOTTOMRIGHT
        ROCK_DOWN
        ROCK_LEFT
        ROCK_RIGHT
        ROCK_TOPLEFT
        ROCK_TOPRIGHT
        ROCK_UP
        SAND_TILE
        SPIKE_HIDDEN
        SPIKE_SHOWN
        TOWER
        TREE_TILE
        UNKNOWN_ASSET
        WATER_TILE
      }
    }
  }
  

  namespace joc {
    namespace assets {
      class joc.assets.SpriteSheet {
          {static} + SPRITE_HEIGHT : int
          {static} + SPRITE_WIDTH : int
          {static} - DECAL_SPRITE_HEIGHT : int
          {static} - DECAL_SPRITE_WIDTH : int
          - spriteImage : BufferedImage
          + SpriteSheet()
          + crop()
          + getAsset()
          + getAssetTypeByNumber()
          + getSpriteImage()
          {static} + rotate()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
