@startuml

title __WINDOW's Class Diagram__\n

  namespace joc {
    namespace window {
      class joc.window.GameWindow {
          {static} + DEFAULT_FPS : int
          {static} - FRAMES_BEFORE_SHUTDOWN_DEFAULT : int
          {static} - SPRITE_SHEET_DEFAULT_LOCATION : String
          - drawingCanvas : Canvas
          - enemies : List<Enemy>
          - fps : int
          - framesBeforeShutdown : int
          - horizontalSpriteCount : int
          {static} - instance : GameWindow
          - mapToLoad : String
          - projectiles : List<Projectile>
          - score : int
          - verticalSpriteCount : int
          + buildComponents()
          + buildLayout()
          + buildListeners()
          + buildWindow()
          + enemyThrowsArrow()
          + enemyThrowsRock()
          + getEnemies()
          {static} + getInstance()
          + getPlayer()
          + getScore()
          + initialize()
          + playerThrowsRock()
          + redraw()
          + setFps()
          + setMapToLoad()
          + setScore()
          + startGame()
          + update()
          - GameWindow()
          - countHighScore()
          - countKeys()
          - updateScoreIntoDatabase()
          - waitBeforeExit()
      }
    }
  }
  

  joc.window.GameWindow -up-|> javax.swing.JFrame
  joc.window.GameWindow o-- joc.character.EnemyAI : enemyAI
  joc.window.GameWindow o-- joc.map.Map : map
  joc.window.GameWindow o-- joc.listener.MovementListener : movementListener
  joc.window.GameWindow o-- joc.player.Player : player
  joc.window.GameWindow o-- joc.assets.SpriteSheet : sheet
  joc.window.GameWindow o-- joc.window.ui.UI : ui


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
